{application,collector,
             [{description,"collector"},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib,lager,mnesia]},
              {mod,{collector_app,[]}},
              {env,[]},
              {modules,[collector,collector_acceptor,collector_app,
                        collector_infodb,collector_listener,collector_sup]}]}.
